kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- git-ops
- cert-manager
- cluster-autoscaler
- efs-driver
- service-discovery
- ingress
- metrics
- monitoring
- security
- health
