kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# These resources are specific to AWS at the moment and not included in the out-of-the-box configuration.
- https://github.com/sura8257/ping-cloud-base.git/k8s-configs/cluster-tools/cert-manager/route53?ref=pdo-1133-core-dns
- https://github.com/sura8257/ping-cloud-base.git/k8s-configs/cluster-tools/cluster-autoscaler/aws?ref=pdo-1133-core-dns
- https://github.com/sura8257/ping-cloud-base.git/k8s-configs/cluster-tools/monitoring/container-insights?ref=pdo-1133-core-dns

# This includes all the generic cloud-agnostic tools, like ingress, logging, service discovery, etc.
- https://github.com/sura8257/ping-cloud-base.git/k8s-configs/cluster-tools?ref=pdo-1133-core-dns

# Include flux CD here so flux can update itself in the future
- https://github.com/sura8257/ping-cloud-base.git/k8s-configs/cluster-tools/git-ops?ref=pdo-1133-core-dns
- known-hosts-config.yaml

- https://github.com/sura8257/ping-cloud-base.git/k8s-configs/cluster-tools/core-dns/dns?ref=pdo-1133-core-dns

patchesStrategicMerge:

### All secrets used by supporting tools ###
- secrets.yaml

### Lets encrypt ACME certificate issuer for the cluster ###
- |-
  apiVersion: certmanager.k8s.io/v1alpha1
  kind: ClusterIssuer
  metadata:
    name: letsencrypt-prod
  spec:
    acme:
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      email: dev@dev-suraj.ping-demo.com
      solvers:
      - dns01:
          route53:
            region: us-west-2
        selector:
          dnsZones:
          - dev-suraj.ping-demo.com

### Lets encrypt ACME certificate for all endpoints ###
- |-
  apiVersion: certmanager.k8s.io/v1alpha1
  kind: Certificate
  metadata:
    name: acme-tls-cert
    namespace: cert-manager
  spec:
    dnsNames:
    - '*.dev-suraj.ping-demo.com'
    commonName: dev-suraj.ping-demo.com

### External DNS service account ###
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: external-dns
    namespace: external-dns
    annotations:
      purpose: service-account-for-external-dns
      

### Additional args to the flux deployment object ###
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: flux
    namespace: flux
  spec:
    template:
      spec:
        containers:
        - name: flux
          args:
          - --manifest-generation=true
          - --listen-metrics=:3031
          - --git-poll-interval=60s
          - --git-url=git@github.com:sura8257/flux-test.git
          - --git-branch=dev
          - --git-path=k8s-configs
          volumeMounts:
          - name: ssh-config
            mountPath: /root/.ssh
        volumes:
        - name: ssh-config
          configMap:
            name: flux-ssh-config
            defaultMode: 0644

### Cloud-watch logging and monitoring ###
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cluster-info
    namespace: amazon-cloudwatch
  data:
    cluster.name: dev
    logs.region: us-west-2

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: cwagentconfig
    namespace: amazon-cloudwatch
  data:
    # Configuration is in Json format. No matter what configure change you make,
    # please keep the Json blob valid.
    cwagentconfig.json: |
      {
        "agent": {
          "region": "us-west-2"
        },
        "logs": {
          "metrics_collected": {
            "kubernetes": {
              "cluster_name": "dev",
              "metrics_collection_interval": 60
            }
          },
          "force_flush_interval": 5
        }
      }

patchesJson6902:

### Change the default TLS secret for the ingress controllers ###
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
    namespace: ingress-nginx-private
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --default-ssl-certificate=ping-cloud/acme-tls-cert

- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller
    namespace: ingress-nginx-public
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --default-ssl-certificate=ping-cloud/acme-tls-cert

### Cluster auto-scaler ###
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cluster-autoscaler
    namespace: kube-system
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/command/-
      value:
        --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/dev
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: AWS_REGION
          value: us-west-2

# Change the namespace of the ACME certificate to the ping-cloud namespace
- target:
    group: certmanager.k8s.io
    version: v1alpha1
    kind: Certificate
    name: acme-tls-cert
    namespace: cert-manager
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ping-cloud

# Configure external-dns to only own the hosted zone for the tenant domain
- target:
    group: apps
    version: v1
    kind: Deployment
    name: external-dns
    namespace: external-dns
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value:
        --domain-filter=dev-suraj.ping-demo.com.

### Logs dashboard ###
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: kibana-ingress
    namespace: elastic-stack-logging
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: logs.dev-suraj.ping-demo.com
    - op: replace
      path: /spec/rules/0/host
      value: logs.dev-suraj.ping-demo.com

### Monitoring dashboard ###
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: grafana-ingress
    namespace: prometheus
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: monitoring.dev-suraj.ping-demo.com
    - op: replace
      path: /spec/rules/0/host
      value: monitoring.dev-suraj.ping-demo.com

### Prometheus Endpoint ###
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: prometheus-ingress
    namespace: prometheus
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: prometheus.dev-suraj.ping-demo.com
    - op: replace
      path: /spec/rules/0/host
      value: prometheus.dev-suraj.ping-demo.com



### Edit CloudWatch Logging Configuration ###
#generatorOptions:
#  disableNameSuffixHash: false
#configMapGenerator:
#  - name: fluentd-config
#    namespace: amazon-cloudwatch
#    behavior: merge
#    files:
#      - containers.conf