apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ping-cloud
    cluster: pingaccess-cluster
    role: pingaccess-engine
  name: pingaccess
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ping-cloud
    cluster: pingaccess-cluster
    role: pingaccess-admin
  name: pingaccess-admin
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ping-cloud
    role: pingdatasync
  name: pingdatasync
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ping-cloud
    class: pingdirectory-server
    role: pingdirectory
  name: pingdirectory
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ping-cloud
    cluster: pingfederate-cluster
    role: pingfederate-engine
  name: pingfederate
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ping-cloud
    cluster: pingfederate-cluster
    role: pingfederate-admin
  name: pingfederate-admin
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: prometheus
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ping-cloud
    cluster: pingaccess-was-cluster
    role: pingaccess-was-engine
  name: pingaccess-was
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ping-cloud
    cluster: pingaccess-was-cluster
    role: pingaccess-was-admin
  name: pingaccess-was-admin
  namespace: ping-cloud
$patch: delete

---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
  labels:
    app: newrelic-license-secret-exporter
  name: newrelic-license-secret-exporter
  namespace: newrelic
$patch: delete
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 1.9.8
    helm.sh/chart: kube-state-metrics-2.13.2
    nri-bundle.version: 4.5.8
  name: nri-bundle-kube-state-metrics
  namespace: newrelic
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-cloud
    role: p14c-bom-service
  name: p14c-bom-service
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-cloud
    role: p14c-bootstrap
  name: p14c-bootstrap
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-cloud
    role: p14c-oauth-service
  name: p14c-oauth-service
  namespace: ping-cloud
$patch: delete


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-cloud
    role: pingcloud-healthcheck
  name: pingcloud-healthcheck
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-cloud
  name: pingdelegator
  namespace: ping-cloud
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: prometheus
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/name: nri-kube-events
    app.kubernetes.io/version: 1.8.0
    helm.sh/chart: nri-kube-events-2.2.4
    nri-bundle.version: 4.5.8
  name: nri-bundle-nri-kube-events
  namespace: newrelic
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/name: nri-metadata-injection
    app.kubernetes.io/version: 1.7.0
    helm.sh/chart: nri-metadata-injection-3.0.4
    nri-bundle.version: 4.5.8
  name: nri-bundle-nri-metadata-injection
  namespace: newrelic
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/name: nri-prometheus
    app.kubernetes.io/version: 2.16.1
    helm.sh/chart: nri-prometheus-2.1.5
    nri-bundle.version: 4.5.8
  name: nri-bundle-nri-prometheus
  namespace: newrelic
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nri-bundle
    app.kubernetes.io/name: newrelic-infrastructure
    app.kubernetes.io/version: 3.2.0
    helm.sh/chart: newrelic-infrastructure-3.5.3
    nri-bundle.version: 4.5.8
  name: nri-bundle-nrk8s-ksm
  namespace: newrelic
$patch: delete


---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: healthcheck-cluster-health
  namespace: health
$patch: delete

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ping-cloud
  name: pingaccess-periodic-backup
  namespace: ping-cloud
$patch: delete

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ping-cloud
  name: pingaccess-was-periodic-backup
  namespace: ping-cloud
$patch: delete

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ping-cloud
    role: pingdirectory
  name: pingdirectory-periodic-backup
  namespace: ping-cloud
$patch: delete

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ping-cloud
  name: pingfederate-periodic-backup
  namespace: ping-cloud
$patch: delete

---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
  labels:
    app: ping-cloud
    role: pingone-configurator
  name: pingone-configurator
  namespace: ping-cloud
$patch: delete

